### ISSUE TITLE
GetToken does not support query parameters

### ISSUE THREAD

**Issue by phoorichet** [binance-chain/go-sdk#57] opened 2019-07-18 08:54 UTC
Query `GetToken` function does not expose query params to the caller.

https://github.com/binance-chain/go-sdk/blob/98a01c4963488fb43ade98680ff8158c41e12030/client/query/get_tokens.go#L10-L12

In the API reference, [`Get tokens list`](https://docs.binance.org/api-reference/dex-api/paths.html#apiv1tokens) allows limit and offset so the client can optionally manipulate these values.

When the number of issued tokens is more than the default limit (which is 500), they got cut off. Thus, `GetToken` does not return the correct list of all tokens.

**Comment by guagualvcha** [comment] 2019-07-18 11:18
thks for your report. The issue is going to fixed in  https://github.com/binance-chain/go-sdk/pull/58

**Closed** 2019-07-22 05:36 UTC
